version: '3.8'
services:
  portfolio-app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - '3000:3000'
    expose:
      - '3000'
    stdin_open: true
    tty: true

networks:
  default:
    name: nginx-proxy-manager
    external: true
